name: tinylog
version: 0.0.2
description: >-
  An tinylog lib.
author: ZhiFeng Hu <hufeng1987@gmail.com>
homepage: https://github.com/netroby/dart-tinylog
documentation: https://github.com/netroby/dart-tinylog
environment:
  sdk: '>=2.0.0 <3.0.0'